find_path(BGFX_INCLUDE_DIR bgfx.h)
find_library(BGFX_LIBRARY NAMES bgfx)

set(BGFX_INCLUDE_DIRS ${BGFX_INCLUDE_DIR})
set(BGFX_LIBRARIES ${BGFX_LIBRARY})

find_package_handle_standard_args(BGFX DEFAULT_MSG BGFX_LIBRARY BGFX_INCLUDE_DIR)
mark_as_advanced(BGFX_FOUND BGFX_INCLUDE_DIR BGFX_LIBRARY)
